events {}

http {
    upstream stable_backend {
        server host.docker.internal:5001 weight=9;
    }
    upstream canary_backend {
        server host.docker.internal:5002 weight=1;
    }
    split_clients "${remote_addr}" $backend {
        90% stable;
        10% canary;
    }
    server {

        listen 80;

        location / {

            if ($variant = canary) {
                proxy_pass http://canary_backend;
                break;
            }

            proxy_pass http://stable_backend;
        }
    }
}